export const ALL_TOOLS = [
    [
        "java",
        "java.com"
    ],
    [
        "python",
        "python.org"
    ],
    [
        "javascript",
        "developer.mozilla.org/es/docs/Web/JavaScript"
    ],
    [
        "typescript",
        "typescriptlang.org"
    ],
    [
        "cpp",
        "w3schools.com/cpp/cpp_intro.asp"
    ],
    [
        "spring",
        "spring.io"
    ],
    [
        "fastapi",
        "fastapi.tiangolo.com"
    ],
    [
        "nodejs",
        "nodejs.org"
    ],
    [
        "react",
        "react.dev"
    ],
    [
        "astro",
        "astro.build"
    ],
    [
        "tailwind",
        "tailwindcss.com"
    ],
    [
        "mysql",
        "myssql.com"
    ],
    [
        "postgresql",
        "postgresql.org"
    ],
    [
        "mongo",
        "mongodb.com"
    ],
    [
        "aws",
        "aws.amazon.com"
    ],
    [
        "docker",
        "docker.com"
    ],
    [
        "git",
        "git-scm.com"
    ],
    [
        "linux",
        "wikipedia.org/wiki/GNU/Linux"
    ],
    [
        "nextjs",
        "nextjs.org"
    ],
    [
        "kafka",
        "kafka.apache.org"
    ],
    [
        "kubernetes",
        "kubernetes.io"
    ],
    [
        "bun",
        "bun.com"
    ]
];

export const TOOLS_PART_1 = ALL_TOOLS.slice(0, Math.ceil(ALL_TOOLS.length / 2));
export const TOOLS_PART_2 = ALL_TOOLS.slice(Math.ceil(ALL_TOOLS.length / 2));
