export const ALL_TOOLS = [
    [
        "java",
        "java.com"
    ],
    [
        "python",
        "python.com"
    ],
    [
        "javascript",
        "cpp.com"
    ],
    [
        "typescript",
        "cpp.com"
    ],
    [
        "cpp",
        "cpp.com"
    ],
    [
        "spring",
        "java.com"
    ],
    [
        "fastapi",
        "python.com"
    ],
    [
        "nodejs",
        "cpp.com"
    ],
    [
        "react",
        "cpp.com"
    ],
    [
        "astro",
        "cpp.com"
    ],
    [
        "tailwind",
        "cpp.com"
    ],
    [
        "mysql",
        "myssql.com"
    ],
    [
        "postgresql",
        "myssql.com"
    ],
    [
        "mongo",
        "myssql.com"
    ],
    [
        "aws",
        "aws.com"
    ],
    [
        "docker",
        "docker.com"
    ],
    [
        "git",
        "docker.com"
    ],
    [
        "linux",
        "docker.com"
    ]
];

export const TOOLS_PART_1 = ALL_TOOLS.slice(0, Math.ceil(ALL_TOOLS.length / 2));
export const TOOLS_PART_2 = ALL_TOOLS.slice(Math.ceil(ALL_TOOLS.length / 2));
